version: "3.8"

services:
  mcp-teradata:
    build: .
    container_name: mcp-teradata
    environment:
      # Database connection
      - DATABASE_URI=teradatasql://user:passwd@host/db
      
      # MCP Transport configuration
      # Options: stdio, http, sse, streamable-http
      - ENV PYTHONUNBUFFERED=1
      - ENV MCP_TRANSPORT=streamable-http
      - ENV MCP_PATH=/mcp/
      - ENV MCP_HOST=0.0.0.0
      - ENV MCP_PORT=8000 # For streamable-http transport

      # Authentication (optional)
      #- KEYCLOAK_ENABLED=true
      #- KEYCLOAK_SERVER_URL=http://your-keycloak:8080
      #- KEYCLOAK_REALM_NAME=mcp-realm
      #- KEYCLOAK_CLIENT_ID=mcp-teradata
      #- KEYCLOAK_CLIENT_SECRET=
    ports:
      - "8000:8000"
    restart: unless-stopped