version: "3.8"

services:
  mcp-teradata:
    build: .
    container_name: mcp-teradata
    environment:
      - DATABASE_URI=teradatasql://user:passwd@host/db
    ports:
      - "8000:8000"
    restart: unless-stopped